name: 'dbt_transform'
version: '1.0.0'

profile: 'dbt_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ============================================================
# MODEL CONFIGURATIONS
# ============================================================
# Folder structure: models/{layer}/{sport}/
# Schema pattern: {layer}_{sport}
# ============================================================

models:
  dbt_transform:

    # ----- STAGING LAYER -----
    # Light cleaning, 1:1 with source tables
    # Materialized as views (always fresh)
    staging:
      +materialized: view
      cfb:
        +schema: staging_cfb
      cbb:
        +schema: staging_cbb

    # ----- INTERMEDIATE LAYER -----
    # Business logic, joins, window functions
    # Foundation tables as tables, others as views
    intermediate:
      +materialized: view
      cfb:
        +schema: intermediate_cfb
      cbb:
        +schema: intermediate_cbb

    # ----- MARTS LAYER -----
    # Final consumption layer for ML/API
    # Materialized as tables for query performance
    marts:
      +materialized: table
      cfb:
        +schema: marts_cfb
      cbb:
        +schema: marts_cbb

# ============================================================
# VARIABLES
# ============================================================
vars:
  # Rolling window sizes for features
  rolling_windows: [3, 5, 10, 20]

  # Teaser point adjustments
  teaser_points: [6, 7, 8, 10, 12]

  # Current season (for filtering)
  current_season: 2024
