version: 2

models:
  # =====================================================
  # CORE GAME MODELS
  # =====================================================

  - name: int_cbb_game_outcomes
    description: |
      Canonical error space model - defines reality vs Vegas.
      Joins games with betting lines and calculates cover margins and total errors.
    columns:
      - name: game_id
        description: Primary key for game
        tests:
          - unique
          - not_null
      - name: cover_margin_home
        description: |
          Points by which home covered the spread.
          Positive = home covered, Negative = home failed to cover.
      - name: total_error
        description: |
          How far total landed from O/U line.
          Positive = game went over, Negative = went under.
      - name: ats_win_home
        description: |
          1 = home covered, 0 = home didn't cover, NULL = push

  - name: int_cbb_team_game
    description: |
      Team perspective expansion - converts game-level to team-level rows.
      Each game produces TWO rows (one for each team).
      All metrics are from the TEAM's perspective.
    columns:
      - name: game_id
        description: Game identifier
        tests:
          - not_null
      - name: team_id
        description: Team identifier
        tests:
          - not_null
      - name: team_game_number
        description: Sequential game number for the team within the dataset
      - name: closing_spread_team
        description: |
          Spread from team's perspective.
          Positive = team is underdog, Negative = team is favorite.
      - name: cover_margin_team
        description: |
          Cover margin from team's perspective.
          Positive = team covered, Negative = team didn't cover.

  # =====================================================
  # SHAPE DESCRIPTOR MODELS
  # =====================================================

  - name: int_cbb_team_spread_behavior
    description: |
      Rolling window metrics for spread/cover behavior.
      Quantifies how tightly a team plays around the spread.
      Uses ROWS BETWEEN N PRECEDING AND 1 PRECEDING for no leakage.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: stddev_cover_margin_last10
        description: Standard deviation of cover margin over last 10 games
      - name: within_10_rate_last10
        description: Rate of games where team covered or failed by less than 10 points

  - name: int_cbb_team_total_behavior
    description: |
      Rolling window metrics for over/under total behavior.
      Quantifies stability around O/U totals.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: over_rate_last10
        description: Rate of overs in last 10 games

  - name: int_cbb_team_trend_state
    description: |
      Short-term ATS/total trends and variance contraction signals.
      Captures momentum and stabilization patterns.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: ats_streak
        description: |
          Current ATS streak. Positive = winning streak, Negative = losing streak.
      - name: spread_variance_contraction_3v10
        description: |
          Ratio of short-term to long-term variance.
          Less than 1 = variance contracting = team stabilizing.

  - name: int_cbb_team_market_profile
    description: |
      What lines the team typically faces.
      Low stddev = Vegas has consistent view of team.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: typical_spread_bucket_last10
        description: Categorical bucket for typical spread faced
        tests:
          - accepted_values:
              values: ['heavy_favorite', 'moderate_favorite', 'slight_favorite',
                       'slight_underdog', 'moderate_underdog', 'heavy_underdog']

  - name: int_cbb_team_location_split
    description: |
      Separate home vs away volatility profiles.
      Identifies road warriors and home-dependent teams.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: is_road_warrior
        description: True if team performs better on road with lower variance
      - name: is_home_dependent
        description: True if team is much better at home
      - name: road_collapse_risk
        description: True if team has high downside tail rate on road

  - name: int_cbb_team_tail_risk
    description: |
      Explicit blowout frequency for teaser blow-through risk.
      Core model for teaser safety assessment.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: downside_tail_10_rate_last10
        description: Rate of games where team failed to cover by 10+ points
      - name: teaser_risk_tier
        description: Risk classification for teasers
        tests:
          - accepted_values:
              values: ['very_low_risk', 'low_risk', 'moderate_risk', 'high_risk', 'very_high_risk']

  # =====================================================
  # MATCHUP MODEL
  # =====================================================

  - name: int_cbb_matchup_variance
    description: |
      Combined matchup variance interaction.
      Combines both teams' variance profiles into game-level predictions.
    columns:
      - name: game_id
        tests:
          - unique
          - not_null
      - name: teaser_matchup_quality
        description: Overall quality tier for teaser betting
        tests:
          - accepted_values:
              values: ['premium', 'good', 'fair', 'avoid']
      - name: matchup_teaser_8_survival
        description: Product of both teams' +8 teaser survival rates

  # =====================================================
  # LABELS MODEL
  # =====================================================

  - name: int_cbb_teaser_labels
    description: |
      Target variables for ML models.
      Calculates what would have happened with various teaser adjustments.
    columns:
      - name: game_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: win_teased_6
        description: 1 if +6 teaser would have won, 0 if lost, NULL if push
      - name: win_teased_8
        description: 1 if +8 teaser would have won, 0 if lost, NULL if push
      - name: flip_with_8
        description: True if original ATS loss would have become teaser win with +8
