version: 2

models:
  - name: fct_cbb_teaser_spread_dataset
    description: |
      **FINAL ML-READY TEASER SPREAD DATASET**

      This is the canonical dataset for training teaser prediction models.

      Structure:
      - One row per team-game (so 2 rows per game)
      - Features: All variance/behavior metrics from prior games (NO LEAKAGE)
      - Labels: Actual teaser outcomes (win_teased_6, win_teased_8, etc.)

      Key design decisions:
      - All features computed using ROWS BETWEEN N PRECEDING AND 1 PRECEDING
      - No current-game information in features (only context like spread/total)
      - Labels computed from actual outcomes (for supervised learning)

      Primary use case: Train models to predict teaser win probability.
    columns:
      - name: game_id
        description: Game identifier
        tests:
          - not_null
      - name: team_id
        description: Team identifier
        tests:
          - not_null
      - name: game_date
        description: Date of the game
        tests:
          - not_null

      # Key features
      - name: stddev_cover_margin_last10
        description: |
          Standard deviation of cover margin over last 10 games.
          Lower = more predictable = better for teasers.
      - name: within_10_rate_last10
        description: Rate of games where cover margin was within 10 points
      - name: downside_tail_rate_last10
        description: Rate of games where team failed to cover by 10+ points
      - name: teaser_risk_tier
        description: Risk classification based on tail behavior
      - name: teaser_8_survival_last10
        description: Estimated probability of surviving +8 teaser based on history

      # Key labels
      - name: win_teased_8
        description: |
          TARGET LABEL: 1 if +8 teaser would have won, 0 if lost, NULL if push.
          Primary prediction target for teaser models.
      - name: flip_with_8
        description: True if original ATS loss became teaser win with +8 points

      # Data quality
      - name: has_sufficient_history
        description: True if team has at least 10 prior games in dataset
      - name: data_quality_tier
        description: Classification of data quality based on sample size
        tests:
          - accepted_values:
              values: ['full', 'moderate', 'minimal', 'insufficient']

  - name: fct_cbb_teaser_matchup_dataset
    description: |
      **GAME-LEVEL MATCHUP DATASET FOR TEASERS**

      One row per game with BOTH teams' features combined.
      Use case: When you want to evaluate a matchup holistically.

      Includes:
      - All matchup variance interaction features
      - Both teams' individual features (prefixed home_/away_)
      - Combined metrics (matchup_*)
      - Teaser labels for BOTH teams
      - Parlay-style combined labels

      Primary use case: Evaluate full game matchups, identify premium teaser parlays.
    columns:
      - name: game_id
        description: Game identifier
        tests:
          - unique
          - not_null
      - name: game_date
        description: Date of the game
        tests:
          - not_null

      # Matchup quality
      - name: teaser_matchup_quality
        description: |
          Overall quality tier for teaser betting.
          'premium' = both teams low variance, low blowout risk.
        tests:
          - accepted_values:
              values: ['premium', 'good', 'fair', 'avoid']
      - name: matchup_teaser_8_survival
        description: Product of both teams' +8 teaser survival rates
      - name: combined_stddev_cover_last10
        description: Root sum of squares of both teams' stddev

      # Parlay labels
      - name: both_teams_win_teased_8
        description: |
          1 if BOTH teams' +8 teasers would have won (parlay success).
          Key label for teaser parlay strategies.
      - name: both_teams_win_teased_10
        description: 1 if BOTH teams' +10 teasers would have won
