"""
Generate PostgreSQL DDL from CFB Parquet files.
"""
import re
from pathlib import Path
import pandas as pd
import numpy as np


def to_snake_case(name: str) -> str:
    """Convert camelCase to snake_case."""
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def infer_pg_type(dtype, col_name: str) -> str:
    """Infer PostgreSQL type from pandas dtype."""
    dtype_str = str(dtype).lower()

    # Check column name hints
    if col_name.endswith("_id") and "source" not in col_name:
        return "INTEGER"
    if col_name in ["id"]:
        return "INTEGER"
    if col_name in ["latitude", "longitude", "elevation"]:
        return "NUMERIC(10,6)"
    if "pct" in col_name or "percentage" in col_name:
        return "NUMERIC(10,4)"
    if "rating" in col_name:
        return "NUMERIC(10,2)"

    # Check dtype
    if "int" in dtype_str:
        return "INTEGER"
    if "float" in dtype_str:
        return "NUMERIC"
    if "bool" in dtype_str:
        return "BOOLEAN"
    if "datetime" in dtype_str:
        return "TIMESTAMPTZ"
    if "object" in dtype_str:
        return "TEXT"

    return "TEXT"


def generate_table_ddl(
    table_name: str,
    df: pd.DataFrame,
    primary_keys: list,
    schema: str = "cfb"
) -> str:
    """Generate CREATE TABLE DDL with staging table."""
    # Main table
    lines = [f"-- Table: {table_name}"]
    lines.append(f"CREATE TABLE IF NOT EXISTS {schema}.{table_name} (")

    cols = []
    for col in df.columns:
        pg_type = infer_pg_type(df[col].dtype, col)
        cols.append(f"    {col} {pg_type}")

    cols.append("    load_date TIMESTAMPTZ DEFAULT NOW()")

    # Add primary key
    if primary_keys:
        pk_cols = ", ".join(primary_keys)
        cols.append(f"    PRIMARY KEY ({pk_cols})")

    lines.append(",\n".join(cols))
    lines.append(");")
    lines.append("")

    # Staging table (no PK, for CDC loads)
    lines.append(f"-- Staging table: stg_{table_name}")
    lines.append(f"CREATE TABLE IF NOT EXISTS {schema}.stg_{table_name} (")

    stg_cols = []
    for col in df.columns:
        pg_type = infer_pg_type(df[col].dtype, col)
        stg_cols.append(f"    {col} {pg_type}")

    stg_cols.append("    load_date TIMESTAMPTZ DEFAULT NOW()")
    lines.append(",\n".join(stg_cols))
    lines.append(");")
    lines.append("")

    return "\n".join(lines)


# Table configurations: file -> (table_name, primary_keys)
TABLES = {
    "conferences/conferences.parquet": ("conferences", ["id"]),
    "venues/venues.parquet": ("venues", ["id"]),
    "teams/teams.parquet": ("teams", ["id"]),
    "games/games_2022_2025.parquet": ("games", ["id"]),
    "lines/lines_2022_2025.parquet": ("betting_lines", ["game_id", "provider"]),
    "team_stats/team_stats_2022_2025.parquet": ("game_team_stats", ["game_id", "team"]),
    "game_players/game_players_2022_2025.parquet": ("game_player_stats", ["game_id", "athlete_id", "category", "stat_type"]),
    "team_season_stats/team_season_stats_2022_2025.parquet": ("team_season_stats", ["season", "team"]),
    "player_season_stats/player_season_stats_2022_2025.parquet": ("player_season_stats", ["season", "player_id", "team"]),
}


def main():
    data_dir = Path(__file__).parent.parent.parent.parent / "data" / "cfb" / "raw"
    output_dir = Path(__file__).parent.parent.parent.parent / "data" / "cfb" / "ddl"
    output_dir.mkdir(parents=True, exist_ok=True)

    ddl_lines = ["-- CFB Database Schema", "-- Generated by generate_ddl.py", "", "CREATE SCHEMA IF NOT EXISTS cfb;", ""]

    for file_path, (table_name, pks) in TABLES.items():
        full_path = data_dir / file_path
        if not full_path.exists():
            print(f"  SKIP: {file_path} not found")
            continue

        df = pd.read_parquet(full_path)
        # Convert columns to snake_case
        df.columns = [to_snake_case(col) for col in df.columns]

        ddl = generate_table_ddl(table_name, df, pks)
        ddl_lines.append(ddl)
        print(f"  {table_name}: {len(df.columns)} columns")

    # Write DDL
    ddl_path = output_dir / "create_tables.sql"
    ddl_path.write_text("\n".join(ddl_lines))
    print(f"\nDDL written to: {ddl_path}")


if __name__ == "__main__":
    main()
